import type { Stash } from "./db";
import { hexToRgbString } from "./color";

function dl(content: string, filename: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function safe(name: string): string {
  return name.replace(/[^a-z0-9-_]+/gi, "_").replace(/^_+|_+$/g, "") || "stash";
}

function slug(name?: string, fallbackIdx = 0): string {
  if (!name) return `color-${fallbackIdx + 1}`;
  const base = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return base || `color-${fallbackIdx + 1}`;
}

function uniqueSlugs(stash: Stash): string[] {
  const seen = new Map<string, number>();
  return stash.swatches.map((s, i) => {
    const base = slug(s.name, i);
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    return count === 0 ? base : `${base}-${count + 1}`;
  });
}

export function exportCSS(stash: Stash) {
  if (stash.swatches.length === 0) return;
  const slugs = uniqueSlugs(stash);
  const lines: string[] = [`/* ${stash.name || "Untitled Stash"} — generated by Colour Pantry */`, `:root {`];
  stash.swatches.forEach((s, i) => {
    lines.push(`  --${slugs[i]}: ${s.hex.toUpperCase()};`);
  });
  lines.push(`}`);
  dl(lines.join("\n") + "\n", `${safe(stash.name)}.css`, "text/css");
}

export function exportSCSS(stash: Stash) {
  if (stash.swatches.length === 0) return;
  const slugs = uniqueSlugs(stash);
  const lines: string[] = [`// ${stash.name || "Untitled Stash"} — generated by Colour Pantry`];
  stash.swatches.forEach((s, i) => {
    lines.push(`$${slugs[i]}: ${s.hex.toUpperCase()};`);
  });
  dl(lines.join("\n") + "\n", `${safe(stash.name)}.scss`, "text/x-scss");
}

export function exportTailwind(stash: Stash) {
  if (stash.swatches.length === 0) return;
  const slugs = uniqueSlugs(stash);
  const colors: Record<string, string> = {};
  stash.swatches.forEach((s, i) => {
    colors[slugs[i]] = s.hex.toUpperCase();
  });
  const colorsBody = Object.entries(colors)
    .map(([k, v]) => `        "${k}": "${v}"`)
    .join(",\n");
  const content = [
    `// ${stash.name || "Untitled Stash"} — paste into tailwind.config.js`,
    `module.exports = {`,
    `  theme: {`,
    `    extend: {`,
    `      colors: {`,
    colorsBody,
    `      },`,
    `    },`,
    `  },`,
    `};`,
  ].join("\n");
  dl(content + "\n", `${safe(stash.name)}.tailwind.js`, "text/javascript");
}

export function exportJSON(stash: Stash) {
  if (stash.swatches.length === 0) return;
  const obj = {
    name: stash.name,
    folder: stash.folder,
    createdAt: new Date(stash.createdAt).toISOString(),
    updatedAt: new Date(stash.updatedAt).toISOString(),
    swatches: stash.swatches.map((s) => ({
      hex: s.hex.toUpperCase(),
      name: s.name,
      addedAt: new Date(s.addedAt).toISOString(),
    })),
    gradient: stash.gradient,
    fontPair: stash.fontPair,
  };
  dl(JSON.stringify(obj, null, 2), `${safe(stash.name)}.json`, "application/json");
}

export function exportFigmaTokens(stash: Stash) {
  if (stash.swatches.length === 0) return;
  const slugs = uniqueSlugs(stash);
  const tokens: Record<string, { value: string; type: string }> = {};
  stash.swatches.forEach((s, i) => {
    tokens[slugs[i]] = { value: s.hex.toUpperCase(), type: "color" };
  });
  const out = { color: tokens };
  dl(JSON.stringify(out, null, 2), `${safe(stash.name)}.tokens.json`, "application/json");
}

/** CSV that Adobe products and most palette tools can import */
export function exportCSV(stash: Stash) {
  if (stash.swatches.length === 0) return;
  const lines = ["Name,Hex,R,G,B"];
  stash.swatches.forEach((s) => {
    const r = parseInt(s.hex.slice(1, 3), 16);
    const g = parseInt(s.hex.slice(3, 5), 16);
    const b = parseInt(s.hex.slice(5, 7), 16);
    const safeName = (s.name || s.hex).replace(/"/g, '""');
    lines.push(`"${safeName}",${s.hex.toUpperCase()},${r},${g},${b}`);
  });
  dl(lines.join("\n") + "\n", `${safe(stash.name)}.csv`, "text/csv");
}

export function exportTXT(stash: Stash) {
  if (stash.swatches.length === 0) return;
  const lines = stash.swatches.map((s) => `${s.hex.toUpperCase()}  ${s.name ?? ""}  rgb(${hexToRgbString(s.hex)})`.trim());
  dl(lines.join("\n") + "\n", `${safe(stash.name)}.txt`, "text/plain");
}
